'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PlayerHeightProvider, usePlayerHeight } from "@/context/PlayerHeightContext";
import { ReactNode } from "react";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const AppBody = ({ children }: { children: ReactNode }) => {
  const { playerHeight } = usePlayerHeight();

  return (
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      style={{ paddingBottom: `${playerHeight}px` }}
    >
      {children}
      <Toaster richColors position="top-right" />
    </body>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PlayerHeightProvider>
        <SessionProvider>
          <AppBody>{children}</AppBody>
        </SessionProvider>
      </PlayerHeightProvider>
    </html>
  );
}
