'use client';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import { CookieConsentProvider } from "@/context/CookieConsentContext";
import { CookieBanner } from "@/components/cookie-consent/CookieBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const AppBody = ({ children }: { children: ReactNode }) => {
  return (
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      suppressHydrationWarning
    >
      {children}
      <Toaster richColors position="top-right" />
      <CookieBanner />
    </body>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <CookieConsentProvider>
        <SessionProvider>
          <AppBody>{children}</AppBody>
        </SessionProvider>
      </CookieConsentProvider>
    </html>
  );
}
