FROM node:18-alpine

RUN apk add --no-cache ffmpeg dumb-init

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY . .

RUN npm ci && npm run build

EXPOSE 3002

CMD ["dumb-init", "node", "-r", "tsconfig-paths/register", "dist/src/workers/worker.js"]

